<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aurora.local" name="net.jodah.concurrentunit.WaiterTest" tests="11" failures="0" timestamp="5 Jul 2015 06:15:35 GMT" time="1.291" errors="0">
  <testcase name="shouldFailNullAssertionWithReason" time="0.000" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldSupportThreadWait0WithResumeCount" time="0.256" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldSupportMultipleThreads" time="0.001" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="waitShouldSupportResume" time="0.256" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldSupportSuccessiveResumes" time="0.000" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="waitShouldSupportExceptions" time="0.001" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldThrowWhenResumingWithoutWait" time="0.000" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="waitShouldSupportTimeouts" time="0.013" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldSupportMultipleResumes" time="0.254" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="shouldFailNullAssertionFromWorkerThreadWithReason" time="0.254" classname="net.jodah.concurrentunit.WaiterTest"/>
  <testcase name="waitShouldSupportAssertionErrors" time="0.256" classname="net.jodah.concurrentunit.WaiterTest"/>
</testsuite> <!-- net.jodah.concurrentunit.WaiterTest -->
